"""
utils/types.py - TypeScript type definition emitter for UUID v7.

  emit_types() - print a TypeScript branded UUIDv7 type definition
"""

from __future__ import annotations

_TS_OUTPUT = '''\
/**
 * Branded UUID v7 type for TypeScript.
 * Generated by pendulumium — https://github.com/vszlx4/pendulumium
 *
 * Usage:
 *   import { UUIDv7, isUUIDv7, asUUIDv7 } from "./uuid";
 *
 *   function getUser(id: UUIDv7): User { ... }
 *
 *   const raw: string = "019e2c01-6909-7583-800a-8afe60572a94";
 *   const id: UUIDv7  = asUUIDv7(raw); // throws if invalid
 *   getUser(id);                        // compiles
 *   getUser(raw);                       // TypeError: string is not UUIDv7
 */

/** UUID v7 branded string type. Zero runtime overhead. */
export type UUIDv7 = string & { readonly __brand: "UUIDv7" };

const _UUID_V7_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Return true if *s* is a well-formed UUID v7 string. */
export function isUUIDv7(s: string): s is UUIDv7 {
  return _UUID_V7_RE.test(s);
}

/** Cast *s* to UUIDv7, throwing a TypeError if it is not a valid UUID v7. */
export function asUUIDv7(s: string): UUIDv7 {
  if (!isUUIDv7(s)) {
    throw new TypeError(`Invalid UUID v7: "${s}"`);
  }
  return s as UUIDv7;
}
'''

def emit_types(*, print_output: bool = True) -> str:
  """
  Emit a TypeScript branded UUIDv7 type definition.

  The emitted code defines a branded string type that makes TypeScript
  enforce UUID v7 validity at compile time — a plain string cannot be 
  passed where a UUIDv7 is expected without an explicit cast.

  Args:
    print_output: if True (default), prints to stdout.
                  if False, returns the string silently.

  Returns:
    The TypeScript source code as a string.

  Example:
    >>> emit_types()                          # prints to stdout
    >>> code = emit_types(print_output=False) # capture as string
    >>> with open("uuid.ts", "w") as f:
    ...   f.write(code)
  """
  if print_output:
    print(_TS_OUTPUT)
  return _TS_OUTPUT
